import re

vi_map = {
    'cat_casual': 'Thường ngày',
    'cat_streetwear': 'Đường phố',
    'cat_hobo': 'Du mục',
    'cat_minimal': 'Tối giản',
    'see_more': 'Xem thêm',
    'see_less': 'Ẩn bớt',
    'admin_dashboard_title': 'Bảng điều khiển',
    'admin_greeting': 'Xin chào,',
    'admin_manage_orders': 'Quản lý đơn hàng',
    'admin_tab_all': 'Tất cả',
    'admin_tab_pending': 'Chờ xử lý',
    'admin_tab_confirmed': 'Đã xác nhận',
    'admin_tab_shipping': 'Đang giao',
    'admin_tab_delivered': 'Đã giao',
    'admin_tab_cancelled': 'Đã hủy',
    'admin_tab_review_pending': 'Chờ duyệt',
    'admin_tab_approved': 'Đã duyệt',
    'admin_tab_rejected': 'Bị từ chối',
    'admin_shortcuts': 'LỐI TẮT',
    'admin_pending_orders_shortcut': 'Đơn hàng chờ xử lý',
    'admin_unapproved_reviews_shortcut': 'Đánh giá chưa duyệt',
    'admin_customer_info': 'THÔNG TIN KHÁCH HÀNG',
    'admin_products_label': 'Danh mục sản phẩm',
    'admin_update_status_title': 'CẬP NHẬT TRẠNG THÁI',
    'admin_update_status_btn': 'Cập nhật trạng thái',
    'admin_btn_delete': 'Xóa',
    'admin_error_update_failed': 'Cập nhật thất bại',
    'admin_error_delete_failed': 'Xóa thất bại',
    'admin_error_login_failed': 'Email hoặc mật khẩu không chính xác',
    'admin_stats_revenue': 'DOANH THU',
    'admin_stats_orders': 'ĐƠN HÀNG',
    'admin_stats_users': 'NGƯỜI DÙNG',
    'admin_stats_blogs': 'BÀI VIẾT',
    'admin_stats_reviews': 'ĐÁNH GIÁ',
    'admin_stats_products': 'SẢN PHẨM',
    'admin_growth': 'PHÂN TÍCH TĂNG TRƯỞNG',
    'admin_recent_activity': 'HOẠT ĐỘNG GẦN ĐÂY',
    'status_cancelled': 'Đã hủy',
    'status_pending': 'Chờ xử lý',
    'status_confirmed': 'Đã xác nhận',
    'status_shipping': 'Đang giao',
    'status_delivered': 'Đã giao',
    'label_rate_this_product': 'Đánh giá sản phẩm này',
    'hint_review_comment': 'Chia sẻ trải nghiệm của bạn với sản phẩm này...',
    'error_rate_all_products': 'Vui lòng đánh giá tất cả sản phẩm trước khi gửi',
    'label_add_photos': 'Thêm ảnh',
    'label_your_review': 'Đánh giá của bạn',
    'admin_menu_flash_sale': 'Flash Sale',
    'admin_menu_flashsale': 'Flash Sale',
    'label_flash_sale': 'Flash Sale',
    'admin_search_order_hint': 'Tìm kiếm theo tên khách hàng...',
    'admin_search_product_hint': 'Tìm kiếm theo tên sản phẩm...',
    'admin_search_blog_hint': 'Tìm kiếm theo tiêu đề, tác giả...',
    'admin_search_user_hint': 'Tìm kiếm theo tên, email...',
    'admin_manage_blogs': 'Quản lý bài viết',
    'admin_employee_email_hint': 'Email'
}

zh_map = {
    'cat_casual': '休闲',
    'cat_streetwear': '街头',
    'cat_hobo': '流浪',
    'cat_minimal': '极简',
    'see_more': '查看更多',
    'see_less': '收起',
    'admin_dashboard_title': '仪表盘',
    'admin_greeting': '你好,',
    'admin_manage_orders': '订单管理',
    'admin_tab_all': '全部',
    'admin_tab_pending': '待处理',
    'admin_tab_confirmed': '已确认',
    'admin_tab_shipping': '运输中',
    'admin_tab_delivered': '已送达',
    'admin_tab_cancelled': '已取消',
    'admin_tab_review_pending': '待审核',
    'admin_tab_approved': '已批准',
    'admin_tab_rejected': '已拒绝',
    'admin_shortcuts': '快捷方式',
    'admin_pending_orders_shortcut': '待处理订单',
    'admin_unapproved_reviews_shortcut': '未审核评价',
    'admin_customer_info': '客户信息',
    'admin_products_label': '产品目录',
    'admin_update_status_title': '更新状态',
    'admin_update_status_btn': '更新状态',
    'admin_btn_delete': '删除',
    'admin_error_update_failed': '更新失败',
    'admin_error_delete_failed': '删除失败',
    'admin_error_login_failed': '管理员邮箱或密码不正确',
    'admin_stats_revenue': '收入',
    'admin_stats_orders': '订单',
    'admin_stats_users': '用户',
    'admin_stats_blogs': '博客',
    'admin_stats_reviews': '评价',
    'admin_stats_products': '产品',
    'admin_growth': '增长分析',
    'admin_recent_activity': '最近活动',
    'status_cancelled': '已取消',
    'status_pending': '待处理',
    'status_confirmed': '已确认',
    'status_shipping': '运输中',
    'status_delivered': '已送达',
    'label_rate_this_product': '评价此产品',
    'hint_review_comment': '分享您对该产品的体验...',
    'error_rate_all_products': '请在提交前对所有产品进行评分',
    'label_add_photos': '添加照片',
    'label_your_review': '您的评价',
    'admin_menu_flash_sale': '限时抢购',
    'admin_menu_flashsale': '限时抢购',
    'label_flash_sale': '限时抢购',
    'admin_search_order_hint': '按客户名称搜索...',
    'admin_search_product_hint': '按产品名称搜索...',
    'admin_search_blog_hint': '按标题、作者搜索...',
    'admin_search_user_hint': '按姓名、电子邮件搜索...',
    'admin_manage_blogs': '博客管理',
    'admin_employee_email_hint': '电子邮件'
}

def translate_file(filepath, tmap):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for key, val in tmap.items():
        pattern = r'(<string name="' + key + r'">)(.*?)(</string>)'
        content = re.sub(pattern, r'\g<1>' + val + r'\g<3>', content)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

translate_file('app/src/main/res/values-vi/strings.xml', vi_map)
translate_file('app/src/main/res/values-zh/strings.xml', zh_map)

print('Translation completed!')
